- src/poprox_recommender/nrms.py
Following method 1 as we discussed, moved the similarity matrix logic outside of `generate_recommendations()` to avoid repeated computation for each user. 
Note: did not test yet.
> optimize mmr logic

- src/poprox_recommender/default.py
- src/poprox_recommender/domain/__init__.py
- src/poprox_recommender/domain/article.py
This is a first step toward representing domain concepts like articles, accounts, entities, etc with Python classes instead of dictionaries. That will make it easier for us to validate the data we're working with and know what fields to expect will be present. We'll also get better type-checking since we'll be able to annotate more of the function parameters and return types.
> Use Pydantic models to represent domain concepts, starting with `Article`

- src/poprox_recommender/default.py
- src/poprox_recommender/handler.py
Since Lambdas stay "warm" for a while and hold things in memory after a request, this makes subsequent calls to generate more recs much faster because they don't have to repeat the work of loading the model and tokenizer.
This also removes model-related code from the handler, which should make it generic across different recommenders, and consolidates it into the recommender code, which limits the number of files experimenters will have to edit.
> Move model and tokenizer loading into initialization for performance

- src/poprox_recommender/default.py
- src/poprox_recommender/test_offline.py
Although this still looks like it uses forward slashes, that's just `pathlib`'s way of saying "path separator," and it will translate them to the appropriate backslashes on Windows.
> Use `pathlib` for paths instead of strings for Windows compatibility

- .github/workflows/docker-image.yml
- .github/workflows/run-tests.yml
- README.md
- conda-lock.yml
- pyproject.toml
- tests/test_pfar.py
- tests/test_serverless_offline.py
- tests/test_smoke.py
Adds PyTest tests to CI, and uses pytest to implement a version of the smoketest with both direct Python API calls and using `serverless offline start` to make sure that we don't break the local dev workflow in addition to the Docker image workflow.
It also uses the `actions/cache` action to cache the model data so we don't hit our S3 bucket so often.
> Add CI test to ensure recommender runs directly and with serverless offline

- .pre-commit-config.yaml
- .yamlfmt
- serverless.yml
This switches our pre-commit YAML formatting to use `yamlfmt` instead of writing our own hook around Prettier in the pre-commit config. Only one file has formatting changes.
> Switch to yamlfmt for YAML formatting in pre-commit

- .github/workflows/docker-image.yml
- .github/workflows/run-tests.yml
- conda-lock.yml
- dev/constraints.yml
- dev/environment.yml
- pyproject.toml
This refactors the Conda dependency specifications into `dev/environment.yml`, defining the development tools, and `dev/constraints.yml` providing additional constraints for locking environments.
This provides better categorization of dependencies in the lock file, so we can install the recommenders without the dev dependencies using Conda, and allows easier use of Conda to install only the dev deps when just tooling but not the ability to run code is required (e.g. fetching data to build the Docker image).
Nothing changes from the developer perspective installing their environment from the lock file — all that changes is how we create it.
> Refactor Conda dependency specifications

- README.md
- conda-lock.yml
- dev/environment.yml
- dev/update-dep-lock.sh
- pyproject.toml
This adds a shell script that runs `conda-lock` with the correct inputs and environment variables to ensure that locking is successful regardless of the user's local Conda configuration. It also tweaks a couple of dependency specifications to make sure that the `main` category contains a closure (`conda-lock` is not 100% on achieving that).
Once the upstream conda-lock bug is fixed, we can update this script to add the ability to update only our dependencies.
> Add script to automate reliable relocking

- conda-lock.yml
- src/poprox_recommender/default.py
- src/poprox_recommender/handler.py
- src/poprox_recommender/topics.py
- tests/basic-request.json
- tests/test_pfar.py
- tests/test_smoke.py
Companion PRs:
* https://github.com/CCRI-POPROX/poprox-concepts/pull/6
* https://github.com/CCRI-POPROX/poprox-platform/pull/78
This combines onboarding selections and the topics of clicked articles into a single topic distribution. The five-point scale presented during onboarding is adjusted so that the lowest interest level counts as zero clicks and the highest counts as four clicks, which are then summed with the topics from clicked articles and then normalized before being passed into the PFAR implementation.
> Integrate onboarding topic selections into PFAR diversification

- Dockerfile
- lambda-bootstrap.sh
This PR updates our Docker build to use Conda to build the image from the locked dependencies.
This solves the problem that our main builds are not using locked dependencies for deployment, so it is possible for deployment of `main` to succeed one day but fail later because of external dependency updates. By using locked dependencies, it ensures (mostly) reproducible and durable deployability of the main branch.
> Use Conda to build Docker image from locked dependencies

- src/poprox_recommender/default.py
PFAR is expecting probabilities in the range 0 to 1, and the tuning parameters don't quite work as expected otherwise. One option is to squash our dot products into that range with a sigmoid and interpret the result as a probability that a user is interested in an item
> Pass relevance scores through a sigmoid before PFAR

- src/poprox_recommender/default.py
- src/poprox_recommender/topics.py
- tests/test_pfar.py
The long list of AP topics has a bunch of very fine-grained stuff in it that makes articles look more topically diverse than they really are, but we know that our short list of high-level topics has close to 100% coverage of the stories we've seen so we can use it here to diversify over a narrower set.
> Use the high-level general topics that match onboarding to diversify

- conda-lock.yml
- dev/environment.yml
- pyproject.toml
- src/poprox_recommender/default.py
This removes `pandas` and `swifter` as (non-dev) dependencies, and may also fix a bug in the existing embedding code (judging by the recommendations produced.)
> Simplify article embedding code

- src/poprox_recommender/default.py
- tests/test_select.py
When users sign up, their first newsletter (and any subsequent newsletters before they click an article) should reflect the topics they chose during onboarding. Here we filter the available articles to just those topics and randomly sample from the remaining articles as a simple stop-gap.
> Update "no clicks" default to match onboarding topic selections

- README.md
- serverless/offline.functions.yaml
- tests/conftest.py
- tests/test_serverless_offline.py
This makes 4 improvements to our documentation and test setup to reduce risk of error in local test runs:
1. Add the editable install instructions to README as a part of dev setup
2. Add logic to `conftest.py` (which PyTest runs before importing tests) to auto-detect whether the recommender package is installed in editable mode, and add the `src` directory to the Python search path if it is not.
3. Add logic to the serverless tests to skip running serverless if an environment variable is set, to make it easier to debug the tests themselves by having them ping a manually-started serverless process.
4. Set up Serverless to import from `poprox_recommender`, not `src.poprox_recommender`, so import errors due to incorrect installs happen when Serverless tries to import the handler instead of …
> Improve ease of running tests from repository

- src/poprox_recommender/default.py
- src/poprox_recommender/diversifiers/__init__.py
- src/poprox_recommender/diversifiers/mmr.py
- src/poprox_recommender/diversifiers/pfar.py
- src/poprox_recommender/embedders/__init__.py
- src/poprox_recommender/embedders/article.py
- src/poprox_recommender/embedders/user.py
- src/poprox_recommender/model/__init__.py
- src/poprox_recommender/scorers/__init__.py
- src/poprox_recommender/scorers/article.py
- src/poprox_recommender/topics.py
This doesn't take us all the way to a pipeline abstraction or even a standard component interface, but it helps clarify what the various components we already have in play do and how they fit together. There aren't any (intentional) changes to the functionality here; this just re-organizes the code to make it easier to think about.
> Break the recommendation process apart into independent-ish components

- src/poprox_recommender/default.py
- src/poprox_recommender/embedders/article.py
- src/poprox_recommender/embedders/user.py
The lookup table is only used in the creation of user embeddings, so we can defer constructing it until we actually need it. That avoids the need to return two different types that contain the same information in different formats from the `ArticleEmbedder`, which cleans up the calling code a bit.
> Move article embedding lookup table construction to `UserEmbedder`

- conda-lock.yml
- src/poprox_recommender/default.py
- src/poprox_recommender/diversifiers/mmr.py
- src/poprox_recommender/diversifiers/pfar.py
- src/poprox_recommender/embedders/article.py
- src/poprox_recommender/embedders/user.py
- src/poprox_recommender/scorers/article.py
This builds on the previous refactoring and CCRI-POPROX/poprox-concepts#9 to standardize the component API a bit. After this refactor, every component takes an `ArticleSet` (an extendable wrapper around a list of articles) as the first argument and some take an `InterestProfile` (an extendable wrapper around click histories etc) as the second argument. Additionally, all components return one of these two types.
The mechanism by which components extend either `ArticleSet` or `InterestProfile` with new information that isn't part of their default definitions is Pydantic's ability to accept and set additional attributes beyond those in the class definition, which components can use to create new attributes like `embeddings`, `scores`, etc. I'd like to find a way to make these more visible, …
> Standardize component argument and return types

- src/poprox_recommender/default.py
- src/poprox_recommender/model/__init__.py
This moves model loading into a `get_model` function to defer loading from import to runtime, caching in a global variable. This returns both the tokenizer and scoring model.
> Dynamically cache the recommender at runtime

- src/poprox_recommender/diversifiers/pfar.py
(Based on #45 and the updated state of `main`)
If I understand correctly, the original paper assumes that people prefer providers equally, which we know isn't true when the "providers" are topics. However, limiting the PFAR boost to topics people have actually clicked on (or selected during onboarding) reduces the impact of diversification to only one or two slots out of the ten in our newsletters.
I think the reason is that the set of selected topics grows very quickly since most articles have several high-level topics, so after the first few slots there simply aren't any more topics that haven't already been selected. That's even more true when using the intersection of people's topic preferences with the list of high-level topics (which will be a shorter list.)
> Use equal weights for unselected topics in PFAR

- .pre-commit-config.yaml
- deploy.sh
Add shfmt to pre-commit to format our shell scripts, and run it on the existing scripts.
This is an additional Go-based dependency.
> Add shell formatting to pre-commit

- conda-lock.yml
- dev/.gitignore
- dev/environment.yml
- dev/update-dep-lock.sh
This PR adds a `--freeze-concepts` option to `update-dep-lock.sh` to allow us to update the lock file (e.g. to add a new dependency) **without** also updating the version of `poprox-concepts` in use. This is useful to allow development of things that need new dependencies while someone else is working on updating the recommender to a new `poprox-concepts` version.
Adding the reverse — updating only `poprox-concepts` without other dependencies — is still blocking on conda/conda-lock#652.
> Add ability to update lockfile without updating poprox-concepts

- src/poprox_recommender/data/mind.py
- src/poprox_recommender/test_offline.py
This follows up on #62 to make the offline tests process the MIND test data incrementally instead of pre-instantiating all full recommendation requests in memory.
Right now, the evaluation is unusably slow, likely due to the lack of caching of article text embeddings. The old code had a 10-article limit that resulted in unhelpful evaluations but did let the code finish.
> [!IMPORTANT]
> This also brings a correctness fix to the metrics, as the previous reciprocal rank was always 1, because it looked for *any* logged record instead of only relevant ones.
> Incrementally process MIND data instead of pre-loading all of it

- src/poprox_recommender/default.py
- src/poprox_recommender/test_offline.py
This refactors the `select_articles` logic to create pipelines into separate functions to create personalized and fallback pipelines, and then directly uses the personalized pipeline in `test_offline` instead of calling `select_articles`.
This is Step 1 of my effort to speed up evaluation by caching article embeddings.
> Refactor default pipeline and selection into pipeline constructor functions

- src/poprox_recommender/datachecks.py
- src/poprox_recommender/default.py
- src/poprox_recommender/embedders/article.py
- src/poprox_recommender/model/nrms/__init__.py
- src/poprox_recommender/model/nrms/news_encoder.py
- src/poprox_recommender/test_offline.py
- tests/test_datachecks.py
This adds a cache to cache the article embeddings in a pipeline instance to reduce recomputation in evaluation.
It also adds a `datachecks` module with a function to do assertion checks on tensor sizes with useful error messages.
> Cache article embeddings

- conda-lock-cuda.yml
- conda-lock.yml
- pyproject.toml
- src/poprox_recommender/logging.py
- src/poprox_recommender/test_offline.py
This refactors the logging configuration int a `setup_logging` function (in `poprox_recommenders.logging`) to enable us to easily and consistently set up logging in any CLI tool we build in this repo, and uses this function in the offline test script.
This function also provides more robust and useful logging, including colorized output on terminals automatic log file support, along with an easy API to support `--verbose` command line options.
It also fixes logging, which was broken in #68 because Michael doesn't know how to properly use `logging.dictConfig`.
> Refactor logging configuration into support function + colorize logs

- src/poprox_recommender/components/samplers/uniform.py
- src/poprox_recommender/pipeline.py
- src/poprox_recommender/pytorch/decorators.py
- tests/test_pipeline.py
When components are added to the pipeline, this keeps track of the types of their inputs and outputs in order to validate that components are wired together in a way that provides the right types to the right inputs (so that e.g. flipping the order of component arguments will result in an error.) It also checks at pipeline execution time that the types being returned by components actually match their type annotations.
> Add best-effort type checking at pipeline construction and run time

- .copier-answers.yml
- .gitignore
- .pre-commit-config.yaml
- Dockerfile
- LICENSE.md
- dev/environment.yml
- pyproject.toml
- src/poprox_recommender/__init__.py
This updates the repo to use the new Copier template ([CCRI-POPROX/poprox-repo-template](https://github.com/CCRI-POPROX/poprox-repo-template)).
The actual changes are mostly noise, reordering things with some better comments and to facilitate reusability across POPROX projects.
> Update to use Copier template

- conda-lock-cuda.yml
- conda-lock.yml
- src/poprox_recommender/components/embedders/user.py
- src/poprox_recommender/data/mind.py
- src/poprox_recommender/handler.py
- src/poprox_recommender/topics.py
- tests/components/test_topic_filter.py
- tests/integration/test_smoke.py
- tests/request_data/basic-request.json
- tests/request_data/medium_request.json
- tests/request_data/request_body.json.dvc
- tests/test_joiners.py
- tests/test_topic_classification.py
This will give us more information about each click, including which newsletter it came from and when. That should be useful to us in developing logic that filters out clicks from email link scanners, among other things.
This also requires an update to the request file managed by DVC, which I have not pushed yet in order to avoid breaking the tests on other PRs until we're ready to move forward with this one
Depends on:
* https://github.com/CCRI-POPROX/poprox-concepts/pull/19
* https://github.com/CCRI-POPROX/poprox-storage/pull/32
> Replace `ClickHistory` with a list of `Click` objects

- src/poprox_recommender/components/diversifiers/mmr.py
This is a low-hanging fruit optimization to replace nested loops in MMR with vectorized PyTorch operations. If the embeddings remain on the GPU, then this should be doing most of MMR on the GPU as well.
> Vectorize MMR for speedup

- src/poprox_recommender/components/filters/topic.py
- src/poprox_recommender/components/samplers/uniform.py
- tests/components/test_topic_filter.py
Profiling revealed that the evaluation was spending 10% of its time checking full article objects for equality, I believe while filtering candidates out of the backups.
This PR changes the sampler use article IDs for backup filtering.
> Use article IDs to filter backups to reduce sampling costs

- src/poprox_recommender/components/diversifiers/topic_calibration.py
- src/poprox_recommender/topics.py
This creates article scores from onboarding topic selections when there are no clicks for the model to use. In that case, the normal article scorer returns `None`, which is a signal to downstream components to fill in the gap if they need to.
Here the scores computation is very rough and just good enough to let topic calibration proceed as usual: the weights of onboarding topic selections that match article topics are summed and the resulting vector of article scores is divided by its max value to normalize the scores into the [0.0,1.0] range.
Adding this to topic calibration was the easiest place to start, but I think there's an argument to be made that this could/should be a fallback scorer in all the pipelines with their various rerankers/diversifiers.
> Apply topic calibration even without clicks (using onboarding topics)

- conda-lock-cuda.yml
- conda-lock.yml
- src/poprox_recommender/components/embedders/article.py
- src/poprox_recommender/data/mind.py
- src/poprox_recommender/evaluation/evaluate.py
- tests/components/test_topic_filter.py
- tests/request_data/basic-request.json
- tests/request_data/medium_request.json
- tests/request_data/request_body.json.dvc
- tests/test_joiners.py
These names probably originated with the early articles we scraped directly from AP's website, which were stored with different field names than are commonly used in journalism. Journalists sometimes call these the `hed` and `subhed`/`dek`, so I've adapted those names a bit to be easier for us to use while staying as true to the source domain as I can.
This differentiates the `subhead` (formerly `content`) from the actual text of the article, which we may soon start fetching from AP with additional API calls.
Connected PRs:
* https://github.com/CCRI-POPROX/poprox-concepts/pull/22
* https://github.com/CCRI-POPROX/poprox-storage/pull/40
* https://github.com/CCRI-POPROX/poprox-platform/pull/142
* https://github.com/CCRI-POPROX/poprox-recommender/pull/91
> Rename article `title` and `content` to `headline` and `subhead`

- src/poprox_recommender/lkpipeline/__init__.py
- src/poprox_recommender/lkpipeline/components.py
- src/poprox_recommender/lkpipeline/config.py
- src/poprox_recommender/lkpipeline/nodes.py
- src/poprox_recommender/lkpipeline/runner.py
- tests/lkpipeline/test_component_config.py
- tests/lkpipeline/test_pipeline_clone.py
- tests/lkpipeline/test_save_load.py
This follows up on #83 to do the component type renaming and logic cleanup around `AutoConfig`, etc.
Tentatively, I renamed the callable type alias to `PipelineFunction`, to communicate that you're either adding a component or a function to the pipeline.
> Rename and reorganize component types

- src/poprox_recommender/components/joiners/fill.py
- src/poprox_recommender/default.py
- src/poprox_recommender/lkpipeline/__init__.py
- src/poprox_recommender/lkpipeline/config.py
- src/poprox_recommender/lkpipeline/nodes.py
- src/poprox_recommender/lkpipeline/runner.py
- src/poprox_recommender/lkpipeline/types.py
- tests/lkpipeline/test_lazy.py
- tests/lkpipeline/test_pipeline.py
- tests/lkpipeline/test_save_load.py
- tests/test_joiners.py
This addresses a question early in discussion on fallbacks where @karlhigley suggested that a fallback should be a component. The way I see to do that without excessive recomputation is through lazy node inputs.
This introduces the following changes:
1.  Add a `Lazy` type so that a component can take a `Lazy[T]` instead of `T`, and the pipeline will key off that type declaration to defer computation of that input until it is requested.
2. Reimplement the fallback tests to use lazy nodes.
3. Update the runner to defer computation of lazy inputs.
4. Update the `Fill` POPROX component to take its second input lazily, and only request it if the first set of recommendations is too short.
5. Update the combiner tests to use the new pipeline.
6. Yeet the `use_first_of` method, `FallbackNode`, …
> Replace fallbacks with lazy nodes and components

- tests/integration/test_serverless_offline.py
This updates our local tests against the serverless offline test server to test all configured pipelines. It also switches to the medium request, because the basic request with its single candidate article crashes the diversifiers.
> Test all configured pipelines in the serverless integration test

- .github/workflows/run-tests.yml
- src/poprox_recommender/config.py
- src/poprox_recommender/recommenders.py
- tests/components/test_softmax_sampler.py
- tests/components/test_topic_calibration.py
- tests/integration/test_serverless_offline.py
- tests/integration/test_smoke.py
- tests/test_paths.py
- tests/test_topic_classification.py
This PR fixes our testing situation without model data.
> Fix tests to work without model data

- tests/components/test_softmax_sampler.py
- tests/components/test_topic_calibration.py
- tests/integration/test_smoke.py
The `mark.xfail` marker did not do what I thought it would do — if `condition` was true, it didn't even try to run the test, when I wanted it to only allow the failure to be expected if the condition was true.
This PR replaces `mark.xfail` with exception-catching and imperative `xfail`, so that it does try to run the tests in all cases.
> Fix test xfail logic

- Dockerfile
This updates `Dockerfile` to use `curl` instead of `ADD --chmod`, which was causing compatibility problems with Docker updates. Docker removed support in "legacy" `docker build`, so this option only works with the new `docker-buildx`. We'll probably be on that eventually, and many already are, but I'd rather not have our builds break because Docker pulled a rug, and `RUN` should keep working.
I am doing this, copying the logic from [prefix-dev/pixi-docker](https://github.com/prefix-dev/pixi-docker/) instead of using their images, because I don't want to deal with the potential problems of using a Debian-based image to build and a RedHat-based image to deploy (Amazon Linux is derived from Red Hat / CentOS / Fedora).
> Remove dependency on ADD --chmod working

- README.md
- pixi.lock
- pixi.toml
- pyproject.toml
This PR makes a few dependency changes and cleanups:
- Add an `eval` extra to `pyproject.toml` that includes the dependencies of the eval scripts, so that the API documentation process doesn't error out on importing them.
- Remove Hatch environments and scripts from `pyproject.toml` since we are using Pixi for all of that; useful scripts I recreated as Pixi tasks. The lint scripts I removed, since we are using pre-commit for linting, and I didn't see value in having those definitions in two places.
- Refactor the Pixi features and environments to add `meta` (manipulate project files) and `eval` (run the evaluation) features, and add these to appropriate environments (`dev` and a new `eval` environment).
- Remove `cuda` as a separate feature, and make the `eval` feature automatically …
> Clean up dependency and project specification

- README.md
- pixi.lock
- pixi.toml
Due to problems encountered running `pixi run` with the integrated CUDA environments (possibly due to stricter checks in a pixi update?), this re-adds the separate `-cuda` environments.
> Re-introduce separate CUDA environments

- README.md
- tests/request_data/basic-request.json
This works in the sense that the request doesn't cause an error with pipelines that involve re-rankers, but it surfaces another issue related to deduplication of recommended articles when the pipeline contains a joiner (like `Fill`.) Right now, the returned list of articles will contain each article twice, once from the main recommender and once from the randomly sampled fallback.
> Extend `basic-request.json` to work with re-rankers

- .copier-answers.yml
- .pre-commit-config.yaml
- scripts/upload-shared-data.sh
This adds [gitleaks][] to the Copier template and imports those changes here, updates our other pre-commit hook versions, and replaces our `local` hooks with externally-maintained hooks that have emerged since last setup.
This will reduce the risk of accidentally committing secrets to the repository.
[gitleaks]: https://github.com/gitleaks/gitleaks
> Update pre-commit and copier template with secret scanning

- .dockerignore
- .github/workflows/deploy.yml
- Dockerfile
- deploy.sh
- serverless.yml
Several relatively small improvements to our Docker config:
- configure Serverless to build for `linux/amd64` explicitly
- update deploy.sh to run serverless properly with npx, and only pull necessary DVC data
- bump Pixi version in docker images
- clean up docker image a bit, removing DNF caches (saves 60MB in final image)
- add `outputs/` and `.pixi/` to `.dockerignore`, speeding up Docker build startup a lot
> Small Docker tweaks and cleanups

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .dprint.json
- .gitignore
- .pre-commit-config.yaml
- .vscode/extensions.json
- .vscode/settings.json
- README.md
- pixi.lock
- pixi.toml
- pyproject.toml
This adds a devcontainer configuration to our repository, and documents it as the recommended development workflow.
This should clean up quite a few platform and environment setup problems for development work.
Batch jobs and evaluation should still be done directly in Linux environments, which are still supported.
This also switches our pre-commit hook to use `dprint` instead of `taplo`, because it's easier to install dprint on linux-aarch64 (and having pre-commit hooks depend on executables only inside the Pixi environment doesn't work very well).
> Add devcontainer

- src/poprox_recommender/components/embedders/article.py
- src/poprox_recommender/components/samplers/softmax.py
- src/poprox_recommender/model/nrms/news_encoder.py
This addresses three warnings of varying importance:
* The LK pipeline code warned that `SoftmaxSampler` didn't have an annotated return type
* The HF Tokenizers library warned about a tokenization space clean-up behavior that has been enabled by default but will be disabled in future versions
* The HF Transformers library warned about the absence of an attention mask being passed to DistilBERT, which can (and does!) affect the article embeddings
> Address warnings, including attention mask issue that changes the recs

- .devcontainer/setup.sh
- .github/workflows/docker-image.yml
- .github/workflows/run-tests.yml
- package-lock.json
- package.json
- pixi.lock
- pixi.toml
- serverless/offline.functions.yaml
- src/poprox_recommender/testing.py
- tests/integration/test_all_pipelines.py
This makes the test suites configurable in terms of their targets to test.
- The various `_service` fixtures will make a POPROX service available to a test case.
- The `auto_service` fixture looks at the `POPROX_TEST_TARGET` environment variable to see which fixture to load. Supported values are `local` (run handlers directly), `docker-auto` (build and run a docker container), and `docker` (connect to already-running Docker container). Eventually it will be able to be a URL to connect to a deployed Lambda endpoint.
- Use the tests instead of the separate test script to test the docker container. This now tests all pipelines after building the container.
- Remove `serverless-offline` and its bits.
> Add retargetable test fixtures and test Docker instead of Serverless Local

- pixi.lock
- src/poprox_recommender/components/diversifiers/locality_calibration.py
- src/poprox_recommender/components/diversifiers/mmr.py
- src/poprox_recommender/components/diversifiers/pfar.py
- src/poprox_recommender/components/diversifiers/topic_calibration.py
- src/poprox_recommender/components/embedders/article.py
- src/poprox_recommender/components/embedders/topic_wise_user.py
- src/poprox_recommender/components/embedders/user.py
- src/poprox_recommender/components/filters/topic.py
- src/poprox_recommender/components/joiners/concat.py
- src/poprox_recommender/components/joiners/fill.py
- src/poprox_recommender/components/joiners/interleave.py
- src/poprox_recommender/components/joiners/rrf.py
- src/poprox_recommender/components/rankers/topk.py
- src/poprox_recommender/components/samplers/softmax.py
- src/poprox_recommender/components/samplers/uniform.py
- src/poprox_recommender/components/scorers/article.py
- src/poprox_recommender/evaluation/generate/worker.py
- src/poprox_recommender/evaluation/metrics/__init__.py
- src/poprox_recommender/evaluation/metrics/rbo.py
- src/poprox_recommender/handler.py
- src/poprox_recommender/recommenders.py
- tests/components/test_calibration.py
- tests/components/test_joiners.py
- tests/components/test_onboarding_embedder.py
- tests/components/test_rrf.py
- tests/components/test_softmax_sampler.py
- tests/components/test_topic_filter.py
- tests/integration/test_smoke.py
- tests/test_topic_classification.py
Differentiating these two types allows us to add attributes and methods to each that are specific to either manipulating pools of items or creating ordered lists of items to be recommended, rather than relying on Python primitives and built-ins to create and manipulate lists of articles.
Depends on https://github.com/CCRI-POPROX/poprox-concepts/pull/39
> Split `ArticleSet` into `CandidateSet` and `RecommendationList`

- .github/workflows/check-data-pipeline.yml
- .vscode/settings.json
- scripts/auto-comments.js
- scripts/check-dvc-status.sh
This modifies the “is the pipeline up-to-date?” logic to post a comment back to the PR instead of failing the build.
The job minimizes all prior status comments as "outdated" to reduce PR clutter.
> Post (or update) a comment instead of failing when pipeline is out of date

- src/poprox_recommender/handler.py
- src/poprox_recommender/testing.py
- tests/integration/test_compression.py
We're hitting the upper end of the allowed request size and adding multiple image records per article is pushing us over. I think there are two issues that lead there:
* Our request serialization may not be excluding the raw image metadata attribute/column correctly
* The requests are already large but should be very compressible
This PR attempts to address the second one by checking the `Content-Type` header and decoding/decompressing the request body if the header is set to `application/json+gzip+base64`.
> Add support for compressed request bodies using `gzip`

- Dockerfile
- pyproject.toml
- src/poprox_recommender/api/main.py
- uv.lock
This route accomplishes several things:
* Get recommendation pipelines and models loaded into memory in at least one Lambda instance before we send recommendation requests
* Tell the platform what version of the request/response format this endpoint supports
* Provide the list of available recommenders back to the platform, which allows us to throw better exceptions on the platform side before we ask for a recommender that doesn't exist in the endpoint
It's a bit tricky to test with the current version of the test service, which (reasonably) assumed only one route per endpoint.
> Add `/warmup` route returning protocol version and available pipelines

- src/poprox_recommender/recommenders/__init__.py
- src/poprox_recommender/recommenders/configurations/__init__.py
- src/poprox_recommender/recommenders/load.py
- tests/integration/test_smoke.py
When the `pipeline` option is passed to `select_articles` but is expicitly `None`, this was not correctly detected in the default pipeline fallback logic.
This PR corrects that, falling back when either `pipeline` is missing or is `None`. It also adds a configuration for the default pipeline, both in a constant and in an environment variable, with a `default_pipeline` function to look up the default.
> Fix default recommender pipeline when pipeline=None

- src/poprox_recommender/data/poprox.py
- tests/generate_test_request.py
Two issues observed so far:
1. Some clicked articles are missing in the exported data (just contain the data from the day of 3/25), like the following error shows; so need to add exception check in the `poprox.py` code.
```
Traceback (most recent call last):
File "/workspaces/poprox-recommender/tests/generate_test_request.py", line 60, in <module>
get_single_request()
File "/workspaces/poprox-recommender/tests/generate_test_request.py", line 26, in get_single_request
requests = list(eval_data.iter_profiles())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspaces/poprox-recommender/src/poprox_recommender/data/poprox.py", line 88, in iter_profiles
article = self.lookup_clicked_article(article_row.article_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Add recommender test request generation script

- src/poprox_recommender/model/nrms/news_encoder.py
Since we're going to overwrite the weights with the ones from our `safetensors` file anyway, we can skip loading the original pretrained weights and just load the model architecture here. It's a little faster but it's hard to say how much it'll help when deployed; on my local machine it's ~30% faster but it could be more or less on AWS.
> Load `distilbert` model architecture but not the pre-trained weights

- pyproject.toml
- src/poprox_recommender/components/joiners/score.py
- src/poprox_recommender/recommenders/hooks.py
- src/poprox_recommender/recommenders/load.py
- tests/conftest.py
- uv.lock
This addresses the model-data-overwriting problem by using a LensKit pipeline hook to proactively make a shallow copy of any Pydantic model that is routed to a component as one of its inputs.
> Use LensKit hooks to proactively shallow-copy Pydantic models

- src/poprox_recommender/components/filters/topic.py
- src/poprox_recommender/components/samplers/epsilon_greedy.py
- src/poprox_recommender/recommenders/configurations/mmr.py
- src/poprox_recommender/recommenders/configurations/nrms.py
- src/poprox_recommender/recommenders/configurations/nrms_images.py
- src/poprox_recommender/recommenders/configurations/nrms_topic_exploration.py
- src/poprox_recommender/recommenders/configurations/nrms_topics_static.py
- src/poprox_recommender/recommenders/configurations/pfar.py
- src/poprox_recommender/recommenders/configurations/softmax.py
- src/poprox_recommender/recommenders/configurations/topic_cali.py
- tests/components/test_joiners.py
- tests/components/test_topic_filter.py
This does three things:
* Updates the `TopicFilter` logic to be smarter about how it uses topic prefs to include/exclude articles
* Creates an `EpsilonGreedy` sampler that selects a random article from a candidate pool for 10% of the slots in the newsletter
* Adds both of those to a new recommender based on `nrms_topic_scores` so that 10% of the articles in the newsletter are chosen at random from the filtered candidate pool
> Create a new recommender that adds exploration to `nrms_topic_scores`

- src/poprox_recommender/components/embedders/user_article_feedback.py
- src/poprox_recommender/recommenders/configurations/nrms_article_feedback.py
- src/poprox_recommender/recommenders/configurations/nrms_feedback_filter.py
- src/poprox_recommender/recommenders/configurations/nrms_feedback_filter_exp.py
This change first simplifies the code of the article feedback embedder by inlining methods and condensing the code in the `call()` method from there. Making the step-by-step process clearer enables some additional logging to diagnose issues. The issue here turned out to be that the recommender configuration was setting the feedback types to `positive` and `negative` but the types sent in the request are actually `True` and `False`.
> Fix filtering by feedback type in `UserArticleFeedbackEmbedder`

- src/poprox_recommender/model/nrms/news_encoder.py
- tests/model/nrms/test_attention_padding.py
This might fix Aishwarya's other problem. I think the old code was re-fetching pretrained models from HuggingFace and we didn't realize it.
> Correctly resolve model path for news encoder

- data/MINDlarge_test.zip.dvc
- data/dvc.lock
- data/dvc.yaml
- models/dvc.yaml
- src/poprox_recommender/training/preprocess.py
The MIND Large Test data set does not actually have clicks / relevance signals — it is only providing the test items for users to generate their submissions to the MIND leaderboard.
We also weren't actually using it for anything.
This PR removes it, along with its output in training preprocessing, from our code and workflow.
> Remove MINDlarge_test data
